template:
  path: tower-project.j2
stack_name: example-dev-project
dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml

parameters:
  S3ReadWriteAccessArns:
    - '{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/brad.macdonald@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/phil.snyder@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/rixing.xu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/bryan.fauble@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/dan.lu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/jenny.medina@sagebase.org'
  AllowSynapseIndexing: Enabled
  AccountAdminArns:
    - '{{stack_group_config.sso_admin_role.arn}}'
    - !stack_output_external sagebase-github-oidc-workflows-dev-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
  CostCenter: NO PROGRAM / 000000
